version: "3.8"
services:
  user-service:
    build: ./backend/user-service
    container_name: user-service
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db.qauuhgzcvmktkkathhak.supabase.co:5432/postgres
    ports:
      - "4001:4001"

  event-service:
    build: ./backend/event-service
    container_name: event-service
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db.qauuhgzcvmktkkathhak.supabase.co:5432/postgres
    ports:
      - "4002:4002"

  booking-service:
    build: ./backend/booking-service
    container_name: booking-service
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db.qauuhgzcvmktkkathhak.supabase.co:5432/postgres
    ports:
      - "4003:4003"

  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "4004:4004"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - event-service
      - booking-service
      - notification-service
